name: Run Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 6 * * *"

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      labs: ${{ steps.labs.outputs.labs }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Define Labs
      id: labs
      run: |
        echo labs=$(ls labs | jq -R -s -c 'split("\n")[:-1]') >> "$GITHUB_OUTPUT"

  run-tests:
    runs-on: ubuntu-latest
    needs: define-matrix
    continue-on-error: true
    strategy:
      matrix:
        lab: ${{ fromJSON(needs.define-matrix.outputs.labs) }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v17

    - name: Run
      run: |
        cd labs/${{ matrix.lab }}
        ./lab.sh deploy
        ./lab.sh smoke_test
        ./lab.sh destroy
